contentColumnType: string
fieldGroup: 0a8e3431-6bf0-42ab-b2a8-0c8758e57f22
handle: featureImage
instructions: ''
name: 'Feature Image'
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:b1f5c7ab-bb6f-46c5-80af-69ce9a11387f'
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  previewMode: full
  restrictFiles: '1'
  selectionLabel: ''
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:b1f5c7ab-bb6f-46c5-80af-69ce9a11387f'
  singleUploadLocationSubpath: ''
  source: null
  sources: '*'
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
